// Données des cartes NFC pour l'API Vercel
let cardsData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    company: "Mobydev",
    jobTitle: "Développeur Senior",
    email: "john@mobydev.com",
    phone: "+33 1 23 45 67 89",
    website: "https://johndoe.dev",
    cardCode: "NFC001",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    company: "Mobydev",
    jobTitle: "Designer UX/UI",
    email: "jane@mobydev.com",
    phone: "+33 1 23 45 67 90",
    website: "https://janesmith.pro",
    cardCode: "NFC002",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 3,
    firstName: "Pierre",
    lastName: "Martin",
    company: "Mobydev",
    jobTitle: "Chef de Projet",
    email: "pierre@mobydev.com",
    phone: "+33 1 23 45 67 91",
    website: "https://pierremartin.fr",
    cardCode: "NFC003",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 4,
    firstName: "Marie",
    lastName: "Dubois",
    company: "Mobydev",
    jobTitle: "Consultante Business",
    email: "marie@mobydev.com",
    phone: "+33 1 23 45 67 92",
    website: "https://mariedubois.com",
    cardCode: "NFC004",
    isActive: false,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 5,
    firstName: "Ahmed",
    lastName: "Ben Ali",
    company: "Mobydev",
    jobTitle: "Développeur Mobile",
    email: "ahmed@mobydev.com",
    phone: "+33 1 23 45 67 93",
    website: "https://ahmedbenali.net",
    cardCode: "NFC005",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Johnson",
    company: "Mobydev",
    jobTitle: "Data Analyst",
    email: "sarah@mobydev.com",
    phone: "+33 1 23 45 67 94",
    website: "https://sarahjohnson.io",
    cardCode: "NFC006",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 7,
    firstName: "Lucas",
    lastName: "Garcia",
    company: "Mobydev",
    jobTitle: "DevOps Engineer",
    email: "lucas@mobydev.com",
    phone: "+33 1 23 45 67 95",
    website: "https://lucasgarcia.es",
    cardCode: "NFC007",
    isActive: false,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 8,
    firstName: "Emma",
    lastName: "Wilson",
    company: "Mobydev",
    jobTitle: "Marketing Manager",
    email: "emma@mobydev.com",
    phone: "+33 1 23 45 67 96",
    website: "https://emmawilson.uk",
    cardCode: "NFC008",
    isActive: true,
    createdAt: "2025-06-10T00:14:21.592Z",
    theme: "gradient-blue"
  },
  {
    id: 9,
    firstName: "jean",
    lastName: "batiste",
    company: "Free Sénégal",
    jobTitle: "Community Manager",
    email: "commercial@mobydev.fr",
    phone: "+33 09 55 16",
    website: "https://site-web.com",
    cardCode: "NFC009",
    isActive: true,
    createdAt: "2025-06-09T22:19:06.230Z",
    theme: "gradient-green"
  },
  {
    id: 10,
    firstName: "Test",
    lastName: "Preview",
    company: "Mobydev Test",
    jobTitle: "Testeur",
    email: "test@mobydev.com",
    phone: "+33 123 456 789",
    website: "https://mobydev.com",
    cardCode: "NFC010",
    isActive: true,
    createdAt: "2025-06-09T22:27:31.063Z",
    theme: "gradient-blue"
  },
  {
    id: 11,
    firstName: "Naoufal",
    lastName: "hamouda",
    company: "mobydev",
    jobTitle: "CEO",
    email: "naoufalhamouda@gmail.com",
    phone: "+33 06 67 09 55 16",
    website: "https://www.mobydev.fr/",
    cardCode: "NFC011",
    isActive: true,
    createdAt: "2025-06-10T06:32:02.671Z",
    theme: "gradient-dark"
  }
];

module.exports = { cardsData }; 